### ISSUE TITLE
Add Integration Testing/Testcontainers

### ISSUE THREAD

**Issue by LTCrane4** [LTCrane4/race-management-service#8]
* Testcontainers: https://www.testcontainers.org/

* Testcontainers - Junit5/Jupiter: https://www.testcontainers.org/test_framework_integration/junit_5/

* Integration testing package under <rootDir>/src

* Test Coverage: 1 per endpoint

* PR Template (Optional)

**Comment by teddycrane** [comment]
Closed in PR #10 and #11
